title: Alex Vaillant # your name (or website title) here
logo: "Github picture.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/alexander-vaillant/">View My LinkedIn Profile</a> 
  <a href="file:///C:/Users/tedda/Desktop/Resume/Vaillant%20Resume.pdf" download>View my Current Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: 285264650 # your Google Analytics tracking ID here
